name: Auto Post Frames

on:
  schedule:
    - cron: "*/5 * * * *"  # runs every 5 minutes
  workflow_dispatch:

jobs:
  post_frames:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run posting script
        env:
          PAGE_ID: ${{ secrets.PAGE_ID }}
          PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python - <<'PYCODE'
          import os, glob, requests

          page_id = os.getenv("PAGE_ID")
          token = os.getenv("PAGE_ACCESS_TOKEN")
          repo = os.getenv("GITHUB_REPOSITORY")

          frames = sorted(glob.glob("frames/*.jpg") + glob.glob("frames/*.png"))
          if not frames:
              print("No images found in frames folder.")
              raise SystemExit(0)

          # --- Remember last frame index ---
          last_frame_file = "last_frame.txt"
          if os.path.exists(last_frame_file):
              with open(last_frame_file, "r") as f:
                  last_index = int(f.read().strip() or "0")
          else:
              last_index = 0

          next_index = (last_index + 1) % len(frames)
          frame = frames[next_index]
          with open(last_frame_file, "w") as f:
              f.write(str(next_index))

          # --- Remember caption counter ---
          counter_file = "counter.txt"
          if os.path.exists(counter_file):
              with open(counter_file, "r") as f:
                  last_number = int(f.read().strip() or "0")
          else:
              last_number = 0

          new_number = last_number + 1
          with open(counter_file, "w") as f:
              f.write(str(new_number))

          caption = f"Test frame {new_number:04d}"
          url = f"https://raw.githubusercontent.com/{repo}/main/{frame}"

          print(f"Posting {url} with caption: {caption}")

          r = requests.post(
              f"https://graph.facebook.com/v24.0/{page_id}/photos",
              data={"url": url, "caption": caption, "access_token": token}
          )
          print("Response:", r.status_code, r.text)
          PYCODE

      - name: Commit updated counters
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add last_frame.txt counter.txt
          git commit -m "Update counters [skip ci]" || echo "No changes to commit"
          git push
